# Action Cable Configuration

development:
  adapter: async
  # Async adapter only works within the same process.
  # To trigger cable updates from a console, use the web console inside the dev process.

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ecom_partners_engg_production
  # Optional: These preserve older behavior if needed
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
