default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rakib
  password: rakibhasan
  host: localhost

development:
  <<: *default
  database: armoiar

test:
  <<: *default
  database: armoiar

production:
  primary: &primary_production
    <<: *default
    database: armoiar_production
    username: armoiar
    password: <%= ENV["ARMOIAR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: armoiar_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: armoiar_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: armoiar_production_cable
    migrations_paths: db/cable_migrate
