# Capistrano
lock '3.12.0'

set :application, 'armoiar'
set :repo_url, 'git@github.com:nazrulcse/armoiar.git'

# Default branch is :main (or leave as master)
# ask :branch, proc { `git rev-parse --abbrev-ref HEAD`.chomp }

set :scm, :git
set :rvm_ruby_version, '3.3.5'  # updated for Rails 8

server '173.212.248.182',
       user: 'deployer',
       roles: %w[web app db]

set :linked_files, %w[config/database.yml config/secrets.yml]
set :linked_dirs, %w[
  log tmp/pids tmp/cache tmp/sockets vendor/bundle public/system
  public/assets public/uploads public/spree pdf_files ]

set :keep_releases, 5

namespace :deploy do
  after :finishing, 'deploy:cleanup'
  after 'deploy:publishing', 'deploy:restart'

  desc 'Restart application'
  task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      execute :touch, release_path.join('tmp/restart.txt')
    end
  end

  after :restart, :clear_cache do
    on roles(:web), in: :groups, limit: 3, wait: 10 do
      # execute :rake, 'cache:clear' if needed
    end
  end
end

task :upload_secret_files do
  on roles(:all) do
    execute "mkdir -p #{shared_path}/config"
    upload! "config/application.yml", "#{shared_path}/config/application.yml"
  end
end

desc 'Invoke a rake command on the remote server'
task :invoke, [:command] => 'deploy:set_rails_env' do |task, args|
  on primary(:app) do
    within current_path do
      with rails_env: fetch(:rails_env) do
        rake args[:command]
      end
    end
  end
end
